### ISSUE TITLE
js path typo

### ISSUE THREAD

**Issue by ahm3dkira** [MinaRomany53/UniHub-Template#3]
![image](https://github.com/MinaRomany53/UniHub-Template/assets/50806393/11a47666-8ddb-43b3-8222-d7467eb9b47f)
some files have "JS" in the path instead of "js" which may be trivial on Windows but on Linux and other servers this may fire an error as shown above.

HaVe A nIcE dAy :)

**Comment by MinaRomany53** [comment]
done
